### ISSUE TITLE
is there any video file ?

### ISSUE THREAD

**Issue by jjjan** [bluscreenofjeff/Red-Team-Infrastructure-Wiki#11]
is there any video about this conf talk that may be you send it to me?

**Comment by bluscreenofjeff** [comment]
The BSides NoVA talk was not recorded. 

We just presented at HackMiami this past weekend. That talk was recorded, but we are unsure if/when we will be able to post. I'll update the issue here when I know one way or the other.

**Comment by jeffmcjunkin** [comment]
According to Iron Geek it wasn't recorded :( (http://www.irongeek.com/i.php?page=videos/bsidesnova2017/mainlist)

However, the slides are online at https://speakerdeck.com/rvrsh3ll/doomsday-preppers-fortifying-your-red-team-infrastructure

**Comment by bluscreenofjeff** [comment]
Correct, the BSides NoVa talk wasn't recorded, but a slightly changed version was recorded at HackMiami. To my knowledge, those videos haven't been released yet.

**Comment by bluscreenofjeff** [comment]
I haven't found a copy of the HackMiami presentation video yet. Closing ticket.
