### ISSUE TITLE
Categorisation section

### ISSUE THREAD

**Issue by dmchell** [bluscreenofjeff/Red-Team-Infrastructure-Wiki#12]
Not sure if it's useful, but categorising domains using Chameleon may be of interest to some people when reading the Categorisation section...

https://www.mdsec.co.uk/2017/07/categorisation-is-not-a-security-boundary/
https://github.com/mdsecactivebreach/Chameleon

**Comment by bluscreenofjeff** [comment]
I think it'd be useful! Added Chameleon and the post to the categorization section. Thanks!!
