### ISSUE TITLE
Change in URL

### ISSUE THREAD

**Issue by boodera** [bluscreenofjeff/Red-Team-Infrastructure-Wiki#29]
https://github.com/bluscreenofjeff/Red-Team-Infrastructure-Wiki#other-third-party-c2 -  A stealthy Python based Windows backdoor that uses Github as a command and control server
must now point to the github page https://github.com/maldevel/canisrufus

**Comment by bluscreenofjeff** [comment]
Thank you for the information! I've updated the link in the wiki.
